window.NEBULA_BILLING = {
  currency: "CLP",
  premiumMonthlyPrice: 6990,
  premiumMonthlyLabel: "$6.990 CLP",
  individualNovelPrice: 1500,
  individualNovelLabel: "$1.500 CLP",
  premiumPlanId: "nebula-premium-monthly",
  premiumName: "Nébula Premium Mensual"
};

window.NEBULA_NOVELS = {
  "codigo-nebula-t1": {
    id: "codigo-nebula-t1",
    title: "Código Nébula  Temporada 1",
    sagaTitle: "Código Nébula",
    description: "Temporada 1. Una historia futurista donde nada es lo que parece y cada capítulo abre una nueva grieta en el sistema.",
    cover: "../assets/covers/nebula.jpg",
    baseFolder: "futurista/codigo-nebula",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 5,
    visitas: 1542,
    tags: ["Futurista", "Tecnología", "Suspenso", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "El pulso de la anomalía", description: "Una señal imposible aparece en la red y marca el inicio de una cadena de eventos que nadie logra explicar." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "La ciudad bajo vigilancia", description: "A medida que los datos se cruzan, queda claro que la ciudad entera ha sido observada durante más tiempo del que cualquiera imaginaba." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "El acceso prohibido", description: "Un archivo oculto abre la primera puerta real hacia Nébula, pero entrar tiene un precio que todavía nadie comprende." },
      { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "El eco en el sistema", description: "Una presencia digital empieza a responder desde dentro de la red con patrones demasiado humanos para ser coincidencia." },
      { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "Fragmentos de una verdad", description: "Los registros filtrados revelan que la historia oficial siempre fue una versión editada de algo mucho más oscuro." },
      { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "La clave fantasma", description: "Una credencial que no debería existir reaparece en varios puntos del sistema, conectando nombres borrados hace años." },
      { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "El mapa de los ausentes", description: "Cada nodo de Nébula parece señalar a personas desaparecidas de los archivos públicos, como si alguien las hubiera arrancado del mundo." },
      { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "Zona de silencio", description: "Cuando la comunicación se corta por completo, lo único que queda es avanzar hacia un lugar del que nadie vuelve igual." },
      { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "La caída del protocolo", description: "Los mecanismos de control empiezan a fallar y la frontera entre vigilancia, memoria y consciencia se rompe." },
      { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "Código Nébula", description: "La verdad final sale a la luz: Nébula no era una herramienta, sino una entidad diseñada para decidir quién permanece y quién desaparece." }
    ]
  },

  "codigo-nebula-t2": {
    id: "codigo-nebula-t2",
    title: "Código Nébula  Temporada 2",
    sagaTitle: "Código Nébula",
    description: "Temporada 2. Continúa la historia con nuevas grietas, nuevas amenazas y un sistema cada vez más despierto.",
    cover: "../assets/covers/codigo-nebula-t2.jpg",
    baseFolder: "futurista/codigo-nebula",
    defaultSeason: "temporada2",
    defaultSeasonLabel: "Temporada 2",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 5,
    visitas: 980,
    tags: ["Futurista", "Tecnología", "Suspenso", "Temporada 2"],
    chapters: [
      { num: 1, season: "temporada2", seasonLabel: "Temporada 2", title: "Reinicio", description: "Después de la caída del protocolo, la red vuelve a encenderse desde un lugar inesperado." },
      { num: 2, season: "temporada2", seasonLabel: "Temporada 2", title: "Ecos residuales", description: "Viejos rastros del sistema empiezan a reaparecer en zonas que debían estar muertas." },
      { num: 3, season: "temporada2", seasonLabel: "Temporada 2", title: "El observador", description: "Una nueva presencia parece mirar desde dentro con más control que antes." },
      { num: 4, season: "temporada2", seasonLabel: "Temporada 2", title: "Punto ciego", description: "Un sector fuera del mapa oculta respuestas que nadie estaba listo para encontrar." },
      { num: 5, season: "temporada2", seasonLabel: "Temporada 2", title: "Memoria falsa", description: "Los recuerdos dejan de ser confiables cuando la red empieza a reescribir versiones de la verdad." },
      { num: 6, season: "temporada2", seasonLabel: "Temporada 2", title: "La segunda llave", description: "Un nuevo acceso abre puertas que parecían selladas para siempre." },
      { num: 7, season: "temporada2", seasonLabel: "Temporada 2", title: "El nodo profundo", description: "Más abajo del sistema existe una capa que nadie había logrado tocar." },
      { num: 8, season: "temporada2", seasonLabel: "Temporada 2", title: "Frecuencia cero", description: "La señal desaparece del mundo visible y reaparece en un canal imposible." },
      { num: 9, season: "temporada2", seasonLabel: "Temporada 2", title: "La red responde", description: "Nébula deja de reaccionar y comienza a actuar por voluntad propia." },
      { num: 10, season: "temporada2", seasonLabel: "Temporada 2", title: "Umbral", description: "El grupo descubre que cruzar cierto límite implica ya no poder volver." },
      { num: 11, season: "temporada2", seasonLabel: "Temporada 2", title: "Sin retorno", description: "La ofensiva final obliga a elegir entre destruir la red o desaparecer con ella." },
      { num: 12, season: "temporada2", seasonLabel: "Temporada 2", title: "Nébula despierta", description: "El cierre de temporada revela que el sistema nunca estuvo dormido: solo estaba esperando." }
    ]
  },

  "despues-de-tu-adios-t1": {
    id: "despues-de-tu-adios-t1",
    title: "Después de tu adiós  Temporada 1",
    sagaTitle: "Después de tu adiós",
    description: "Una novela emocional sobre recuerdos, ausencia y todo lo que sigue vivo después de una despedida.",
    cover: "../assets/covers/despues-de-tu-adios.jpg",
    baseFolder: "romance/despues-de-tu-adios",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 4,
    visitas: 1187,
    tags: ["Romance", "Emocional", "Drama", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "La llamada que no debía llegar", description: "Una voz del pasado reabre emociones que parecían enterradas." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "El peso del recuerdo", description: "Cada objeto, cada rincón y cada silencio empiezan a devolver escenas que todavía duelen." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "Lo que dejaste aquí", description: "No todo lo que se pierde desaparece; algunas ausencias toman más espacio que una presencia." }
    ]
  },

  "no-debi-enamorarme-t1": {
    id: "no-debi-enamorarme-t1",
    title: "No debí enamorarme de ti  Temporada 1",
    sagaTitle: "No debí enamorarme de ti",
    description: "Temporada 1. Una historia intensa sobre deseo, decisiones equivocadas y emociones que arden demasiado.",
    cover: "../assets/covers/no-debi-enamorarme.jpg",
    baseFolder: "romance/no-debi-enamorarme",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 4,
    visitas: 2100,
    tags: ["Romance", "Drama", "Pasión", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "La primera mirada", description: "Todo parece normal hasta que una mirada cambia el ritmo de lo que ambos creían controlar." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "Demasiado cerca", description: "La cercanía empieza a incomodar justo cuando ignorarla ya no parece una opción real." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "El error perfecto", description: "Lo que parecía un momento pequeño deja una grieta imposible de cerrar." },
      { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "Lo que no debía pasar", description: "La tensión llega a un punto donde nadie puede seguir fingiendo que no está sintiendo demasiado." },
      { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "La distancia", description: "Tomar distancia no calma nada; solo hace que el deseo se vuelva más evidente." },
      { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "Sin defensa", description: "Cuando las palabras ya no alcanzan, queda al descubierto lo que ambos intentaban esconder." },
      { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "Después del beso", description: "Un solo instante cambia por completo la forma en que se miran y la forma en que pueden seguir." },
      { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "Todo arde", description: "Sentir demasiado empieza a costar más de lo que cualquiera estaba dispuesto a pagar." },
      { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "La caída", description: "Las decisiones se acumulan y el punto de no retorno aparece sin aviso." },
      { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "No debí enamorarme de ti", description: "El final de temporada obliga a elegir entre protegerse o aceptar que ya no hay manera de retroceder." },
      { num: 11, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 11", description: "La historia sigue escalando y las consecuencias ya no pueden ocultarse." },
      { num: 12, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 12", description: "La tensión emocional alcanza un punto crítico antes del cierre." }
    ]
  },

  "no-debi-enamorarme-t2": {
    id: "no-debi-enamorarme-t2",
    title: "No debí enamorarme de ti  Temporada 2",
    sagaTitle: "No debí enamorarme de ti",
    description: "Temporada 2. Nueva temporada, nuevas consecuencias y una historia que sube todavía más la intensidad emocional.",
    cover: "../assets/covers/no-debi-enamorarme-t2.jpg",
    baseFolder: "romance/no-debi-enamorarme",
    defaultSeason: "temporada2",
    defaultSeasonLabel: "Temporada 2",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 4,
    visitas: 1300,
    tags: ["Romance", "Drama", "Pasión", "Temporada 2"],
    chapters: [
      { num: 1, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 1", description: "Nueva temporada, nuevas consecuencias." },
      { num: 2, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 2", description: "La historia retoma desde un punto de dolor y deseo." },
      { num: 3, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 3", description: "Los sentimientos vuelven a mezclarse con decisiones imposibles." },
      { num: 4, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 4", description: "Las heridas del pasado siguen marcando cada paso." },
      { num: 5, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 5", description: "La distancia no logra apagar lo que todavía sigue vivo." },
      { num: 6, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 6", description: "Una nueva decisión amenaza con empeorarlo todo." },
      { num: 7, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 7", description: "El deseo vuelve justo cuando más daño puede causar." },
      { num: 8, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 8", description: "La relación entra en una etapa más oscura y más intensa." },
      { num: 9, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 9", description: "El miedo a perderlo todo deja de ser una amenaza lejana." },
      { num: 10, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 10", description: "Las emociones acumuladas explotan en el peor momento." },
      { num: 11, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 11", description: "Lo que parecía control vuelve a romperse por completo." },
      { num: 12, season: "temporada2", seasonLabel: "Temporada 2", title: "Capítulo 12", description: "El cierre de temporada deja a los protagonistas frente a su verdad final." }
    ]
  },

  "la-ultima-conexion-t1": {
    id: "la-ultima-conexion-t1",
    title: "La última conexión  Temporada 1",
    sagaTitle: "La última conexión",
    description: "A las 02:17 de la madrugada, Daniel recibe mensajes desde su propio número. Lo peor no es quién escribe, sino que esos mensajes saben exactamente lo que está ocurriendo dentro de su habitación.",
    cover: "../assets/covers/la-ultima-conexion.jpg",
    baseFolder: "terror/la-ultima-conexion",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 5,
    visitas: 842,
    tags: ["Terror", "Tecnológico", "Suspenso", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "02:17", description: "El primer mensaje llega a una hora exacta y con una información que nadie más podría tener." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "Desde mi propio número", description: "Responder parece un error, pero ignorarlo es todavía peor." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "Lo que hay detrás de la puerta", description: "Cuando los mensajes describen su habitación al detalle, Daniel entiende que ya no está solo." },
      { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "La conexión sigue abierta", description: "Desconectar el teléfono no detiene nada; solo empeora la manera en que esa presencia se manifiesta." },
      { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "No abras el historial", description: "El pasado digital de Daniel revela algo que nunca debió haber quedado registrado." },
      { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "La voz del audio", description: "Un archivo enviado a la madrugada contiene una voz imposible de escuchar sin quebrarse." },
      { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "Modo avión", description: "Ni apagado, ni sin red, ni desconectado: el contacto sigue llegando." },
      { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "No era una app", description: "La entidad detrás de los mensajes no vive en el teléfono; solo lo usa para entrar." },
      { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "La última videollamada", description: "Aceptar una llamada final abre una escena que no debería existir del otro lado de la pantalla." },
      { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "La última conexión", description: "El cierre de temporada revela que responder fue exactamente lo que esa presencia necesitaba." },
      { num: 11, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 11", description: "La amenaza sigue creciendo y ya no parece posible desconectarse." },
      { num: 12, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 12", description: "La historia profundiza en el verdadero origen de la presencia." }
    ]
  },

  "ya-habias-estado-ahi-t1": {
    id: "ya-habias-estado-ahi-t1",
    title: "Ya habías estado ahí  Temporada 1",
    sagaTitle: "Ya habías estado ahí",
    description: "Volver a casa nunca volvió a sentirse normal. Un cajón abierto, una puerta distinta, objetos fuera de lugar. Al principio parecen detalles mínimos, hasta que entiendes algo peor: alguien ya había estado ahí.",
    cover: "../assets/covers/ya-habias-estado-ahi.jpg",
    baseFolder: "terror/ya-habias-estado-ahi",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 5,
    visitas: 1100,
    tags: ["Terror", "Psicológico", "Suspenso", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "Algo no está igual", description: "Volver a casa se siente distinto desde el primer segundo, aunque todavía no hay una razón clara." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "El cajón abierto", description: "Un detalle mínimo basta para sembrar la idea de que alguien tocó lo que no debía." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "La puerta mal cerrada", description: "La rutina deja de ser confiable cuando cada objeto parece contar una versión distinta de lo ocurrido." },
      { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 4", description: "La tensión sigue aumentando." },
      { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 5", description: "Lo que parecía paranoia empieza a sentirse demasiado real." },
      { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 6", description: "Cada rincón de la casa guarda una señal imposible de ignorar." },
      { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 7", description: "La idea de que alguien estuvo ahí deja de ser una sospecha." },
      { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 8", description: "La verdad detrás de la presencia empieza a revelarse." },
      { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 9", description: "Escapar ya no parece una opción real." },
      { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 10", description: "El final de temporada confirma que nada fue una coincidencia." }
    ]
  },

  "pinochet-t1": {
    id: "pinochet-t1",
    title: "Pinochet  Temporada 1",
    sagaTitle: "Pinochet",
    description: "Una novela histórica intensa sobre poder, control, decisiones militares y el impacto humano de un periodo que marcó para siempre la historia de Chile.",
    cover: "../assets/covers/pinochet_nebula_portada.png",
    baseFolder: "Pinochet",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 5,
    visitas: 2000,
    tags: ["Historia", "Militar", "Política", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 1", description: "Inicio de una historia marcada por poder y ruptura." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 2", description: "La tensión política crece." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 3", description: "La historia entra en un punto de no retorno." },
      { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 4", description: "La historia continúa." },
      { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 5", description: "La historia continúa." },
      { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 6", description: "La historia continúa." },
      { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 7", description: "La historia continúa." },
      { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 8", description: "La historia continúa." },
      { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 9", description: "La tensión alcanza un punto irreversible." },
      { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 10", description: "El poder se consolida mientras el país cambia para siempre." },
      { num: 11, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 11", description: "Las consecuencias humanas ya no pueden ocultarse." },
      { num: 12, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 12", description: "El cierre de temporada deja una herida abierta sobre Chile." }
    ]
  },

  "allende-t1": {
    id: "allende-t1",
    title: "Allende  Temporada 1",
    sagaTitle: "Allende",
    description: "Una historia política y humana sobre liderazgo, convicción y uno de los periodos más decisivos de la historia de Chile.",
    cover: "../assets/covers/allende_portada_nebula.png",
    baseFolder: "allende",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 5,
    visitas: 1800,
    tags: ["Historia", "Política", "Drama", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 1", description: "Comienza una historia marcada por ideales y tensión." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 2", description: "Las decisiones empiezan a cambiarlo todo." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 3", description: "La presión política se vuelve insoportable." },
      { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 4", description: "La historia continúa." },
      { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 5", description: "La historia continúa." },
      { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 6", description: "La historia continúa." },
      { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 7", description: "La historia continúa." },
      { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 8", description: "La historia continúa." },
      { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 9", description: "La historia continúa." },
      { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 10", description: "La historia alcanza su clímax." },
      { num: 11, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 11", description: "La presión política y social alcanza un nivel insoportable." },
      { num: 12, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 12", description: "El país entra en una etapa decisiva donde cada movimiento acerca el desenlace." },
      { num: 13, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 13", description: "Los acontecimientos avanzan hacia un desenlace histórico." },
      { num: 14, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 14", description: "La historia entra en su etapa más oscura y decisiva." },
      { num: 15, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 15", description: "El país enfrenta el peso total de sus fracturas." },
      { num: 16, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 16", description: "El cierre deja marcada para siempre la memoria de Chile." }
    ]
  },

  "golpe-de-estado-t1": {
    id: "golpe-de-estado-t1",
    title: "Golpe de Estado  Temporada 1",
    sagaTitle: "Golpe de Estado",
    description: "Una historia política, social y humana sobre la fractura de un país, la tensión del poder y los días que cambiaron Chile para siempre.",
    cover: "../assets/covers/golpe_estado_nebula.png",
    baseFolder: "historia/golpe-de-estado",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 5,
    visitas: 0,
    tags: ["Historia", "Política", "Drama", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "La antesala", description: "Las tensiones se acumulan en silencio mientras el país se acerca a una ruptura irreversible." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "La orden", description: "Los movimientos militares dejan claro que ya no hay vuelta atrás." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "El día que cambió todo", description: "Las calles, el poder y la historia colisionan en una jornada imposible de olvidar." }
    ]
  },

  "el-precio-del-silencio-t1": {
    id: "el-precio-del-silencio-t1",
    title: "El Precio del Silencio  Temporada 1",
    sagaTitle: "El Precio del Silencio",
    description: "Una historia de corrupción, secretos y una red de poder que empieza a quebrarse desde dentro.",
    cover: "../assets/covers/portada-nebula.jpg",
    baseFolder: "Thriller de corrupción/El Precio del Silencio",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 5,
    visitas: 1600,
    tags: ["Thriller", "Corrupción", "Suspenso", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 1", description: "Una grieta aparece en el sistema." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 2", description: "Los nombres comienzan a salir a la luz." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 3", description: "El silencio empieza a costar demasiado." },
      { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 4", description: "La red empieza a desmoronarse." },
      { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 5", description: "Nadie sabe ya de qué lado está." },
      { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 6", description: "La investigación se intensifica." },
      { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 7", description: "El costo de hablar se vuelve real." },
      { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 8", description: "Las piezas encajan demasiado tarde." },
      { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 9", description: "La caída ya no puede detenerse." },
      { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 10", description: "El sistema revela su verdadero rostro." },
      { num: 11, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 11", description: "Nada vuelve a ser igual." },
      { num: 12, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 12", description: "La presión ya no deja espacio para errores." },
      { num: 13, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 13", description: "Cada decisión empuja la red más cerca del colapso." },
      { num: 14, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 14", description: "La verdad empieza a filtrarse donde más duele." },
      { num: 15, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 15", description: "Las lealtades se quiebran justo antes del golpe final." },
      { num: 16, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 16", description: "Todo se prepara para el golpe final." },
      { num: 17, season: "temporada1", seasonLabel: "Temporada 1", title: "Capítulo 17", description: "El cierre de la historia revela el verdadero precio del silencio." }
    ]
  },

  "suegro-a-la-deriva-t1": {
    id: "suegro-a-la-deriva-t1",
    title: "Suegro a la Deriva  Temporada 1",
    sagaTitle: "Suegro a la Deriva",
    description: "Una comedia con drama y caos familiar donde un paseo termina sacando a flote heridas, secretos y una segunda temporada inevitable.",
    cover: "../assets/covers/suegro-a-la-deriva-t1.jpg",
    baseFolder: "comedia/suegro-a-la-deriva",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 5,
    visitas: 0,
    tags: ["Comedia", "Drama", "Familia", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "El viaje que nadie quería", description: "Un paseo familiar comienza mal desde el primer minuto y deja claro que nadie saldrá igual." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "El primer choque", description: "Las tensiones entre yerno y suegro explotan antes de que aparezca el verdadero problema." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "Sin señal", description: "Aislados y sin salida fácil, las máscaras empiezan a caer." },
      { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "Lo que no se dijo", description: "Viejas heridas familiares resurgen en medio del encierro y el cansancio." },
      { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "El límite", description: "Una discusión feroz obliga a todos a mostrar quiénes son realmente." },
      { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "Nadie se va", description: "Escapar ya no es simple, y la convivencia se vuelve insoportable." },
      { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "El pasado vuelve", description: "Un recuerdo mal enterrado empieza a cambiar la mirada sobre Raúl." },
      { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "La noche larga", description: "La oscuridad, el miedo y el hambre hacen que todo se vuelva más frágil." },
      { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "Punto de quiebre", description: "Una decisión impulsiva deja consecuencias que nadie puede controlar." },
      { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "Demasiado tarde", description: "Cuando intentan recomponerse, descubren que el daño ya está hecho." },
      { num: 11, season: "temporada1", seasonLabel: "Temporada 1", title: "El verdadero problema", description: "La crisis deja claro que el conflicto nunca fue solo el viaje." },
      { num: 12, season: "temporada1", seasonLabel: "Temporada 1", title: "Todo se rompe", description: "Las relaciones se fracturan y la familia deja de parecer familia." },
      { num: 13, season: "temporada1", seasonLabel: "Temporada 1", title: "Sin salida", description: "La tensión escala hasta un punto donde cualquier error puede ser fatal." },
      { num: 14, season: "temporada1", seasonLabel: "Temporada 1", title: "El error", description: "Una mala decisión cambia el rumbo de todos justo antes del desenlace." },
      { num: 15, season: "temporada1", seasonLabel: "Temporada 1", title: "Consecuencias", description: "El peso emocional del viaje cae sobre cada uno de manera distinta." },
      { num: 16, season: "temporada1", seasonLabel: "Temporada 1", title: "Antes del final", description: "Todo parece cerrarse, pero hay algo que todavía no encaja." },
      { num: 17, season: "temporada1", seasonLabel: "Temporada 1", title: "El inicio de algo más", description: "Cuando por fin parece terminar, una revelación deja abierta una nueva tormenta." }
    ]
  },

"luci-t1": {
  id: "luci-t1",
  title: "Luci — Temporada 1",
  sagaTitle: "Luci",
  description: "Una historia intensa de amor, dolor y decisiones que marcan la vida para siempre.",
  cover: "../assets/covers/luci.jpg",
  baseFolder: "romance/luci",
  defaultSeason: "temporada1",
  defaultSeasonLabel: "Temporada 1",
  freeChapters: 3,
  price: "$1.500 CLP",
  rating: 5,
  visitas: 0,
  tags: ["Romance", "Drama", "Emocional"],
  chapters: [
    { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "El comienzo", description: "Todo empezó con una mirada que ninguno de los dos esperaba." },
    { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "La conexión", description: "Una conexión inesperada comienza a crecer entre ellos." },
    { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "El quiebre", description: "Una verdad cambia todo lo que creían conocer." },
    { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "Cartas al futuro", description: "Luci comienza a escribir lo que tal vez no alcance a decir." },
    { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "Bajo la lluvia", description: "Una conversación cambia el rumbo de sus emociones." },
    { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "Las cosas pequeñas", description: "Momentos simples que se vuelven eternos." },
    { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "Secretos de Bruno", description: "No todo es lo que parece en él." },
    { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "El escape", description: "Un día fuera del mundo cambia todo." },
    { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "El primer beso", description: "El momento que ya no tiene vuelta atrás." },
    { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "El miedo", description: "Amar también significa temer perder." },
    { num: 11, season: "temporada1", seasonLabel: "Temporada 1", title: "Distancia", description: "Algo empieza a romperse entre ellos." },
    { num: 12, season: "temporada1", seasonLabel: "Temporada 1", title: "La verdad", description: "Todo sale a la luz." },
    { num: 13, season: "temporada1", seasonLabel: "Temporada 1", title: "El golpe", description: "La vida no avisa antes de cambiarlo todo." },
    { num: 14, season: "temporada1", seasonLabel: "Temporada 1", title: "Resistencia", description: "Seguir adelante se vuelve una decisión." },
    { num: 15, season: "temporada1", seasonLabel: "Temporada 1", title: "El último intento", description: "Cuando todo parece perdido, aún queda algo." },
    { num: 16, season: "temporada1", seasonLabel: "Temporada 1", title: "Despedida", description: "No todas las historias terminan como esperamos." },
    { num: 17, season: "temporada1", seasonLabel: "Temporada 1", title: "Lo que queda", description: "El final que abre algo nuevo." }
  ]
},
  
"area51-protocolo-oculto-t1": {
  id: "area51-protocolo-oculto-t1",
  title: "Area 51  El Protocolo Oculto  Temporada 1",
  sagaTitle: "Area 51  El Protocolo Oculto",
  description: "Temporada 1. Una historia de conspiracion, experimentos secretos, desapariciones y un complejo subterraneo donde la verdad sobre Area 51 podria destruir todo lo que creemos conocer.",
  cover: "../assets/covers/area51-protocolo-oculto.jpg",
  baseFolder: "futurista/area51_protocolo_oculto",
  defaultSeason: "temporada1",
  defaultSeasonLabel: "Temporada 1",
  freeChapters: 3,
  price: "$1.500 CLP",
  rating: 5,
  visitas: 0,
  tags: ["Futurista", "Alienigena", "Conspiracion", "Suspenso", "Temporada 1"],
  chapters: [
    { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "La señal bajo la arena", description: "Una transmision enterrada bajo el desierto activa un protocolo que llevaba decadas dormido." },
    { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "El ingreso prohibido", description: "El equipo entra a una zona restringida y descubre que Area 51 no era solo una base militar." },
    { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "Los cuerpos de vidrio", description: "Detras de un laboratorio sellado aparecen camaras de contencion con algo que no deberia existir." },
    { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "Protocolo Nox", description: "Un archivo clasificado revela que los experimentos no eran humanos y que el contacto nunca se detuvo." },
    { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "Nivel subterraneo nueve", description: "Bajo la instalacion principal existe una estructura mas antigua, mas grande y mucho peor de lo imaginado." },
    { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "La sala de los no registrados", description: "Una lista de nombres borrados del sistema conecta desapariciones civiles con pruebas secretas dentro de la base." },
    { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "Contacto visual", description: "Uno de los sujetos despierta y demuestra una capacidad imposible que cambia toda la operacion." },
    { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "La compuerta negra", description: "Una puerta blindada conduce a una zona donde el tiempo, la energia y la materia parecen comportarse distinto." },
    { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "Ecos de Roswell", description: "Viejos registros militares confirman que lo recuperado en Roswell nunca abandono el pais." },
    { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "Los ingenieros del cielo", description: "La tecnologia hallada en los hangares demuestra que hubo cooperacion entre humanos y algo venido de fuera." },
    { num: 11, season: "temporada1", seasonLabel: "Temporada 1", title: "El duplicado", description: "Uno de los integrantes del equipo descubre que ya habia estado ahi... aunque no lo recuerda." },
    { num: 12, season: "temporada1", seasonLabel: "Temporada 1", title: "Zona de silencio", description: "Las comunicaciones con el exterior se cortan y la base entra en aislamiento total mientras algo empieza a moverse." },
    { num: 13, season: "temporada1", seasonLabel: "Temporada 1", title: "La camara roja", description: "En el nucleo del complejo se conserva un organismo que no esta muerto ni completamente vivo." },
    { num: 14, season: "temporada1", seasonLabel: "Temporada 1", title: "El protocolo oculto", description: "La verdad sale a la luz: Area 51 fue creada para contener una activacion global, no para esconder naves." },
    { num: 15, season: "temporada1", seasonLabel: "Temporada 1", title: "La frecuencia", description: "Una señal emitida desde el subsuelo comienza a llamar a algo que se encuentra fuera de la Tierra." },
    { num: 16, season: "temporada1", seasonLabel: "Temporada 1", title: "Apertura", description: "El sistema de contencion colapsa y el cielo sobre el desierto responde con una presencia imposible de ocultar." },
    { num: 17, season: "temporada1", seasonLabel: "Temporada 1", title: "No estaban viniendo, ya estaban aqui", description: "El cierre de temporada revela que la invasion nunca fue una llegada, sino un despertar desde dentro." }
  ]
},
  
  "mision-peligrosa-t1": {
    id: "mision-peligrosa-t1",
    title: "Misión Peligrosa  Temporada 1",
    sagaTitle: "Misión Peligrosa",
    description: "Una historia de acción militar, traiciones, fuego cruzado y una operación en la costa que termina revelando algo mucho más grande y letal.",
    cover: "../assets/covers/mision-peligrosa.jpg",
    baseFolder: "accion/mision-peligrosa",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 5,
    visitas: 0,
    tags: ["Acción", "Militar", "Suspenso", "Costa", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "La extracción fallida", description: "Una operación nocturna en la costa se sale de control en los primeros minutos y deja al equipo atrapado en territorio enemigo." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "Fuego desde la niebla", description: "Mientras intentan reagruparse bajo fuego cruzado, una emboscada confirma que alguien filtró la misión." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "El hombre que no debía estar ahí", description: "Entre cadáveres, humo y mar revuelto, aparece una figura que conecta la misión con una red más peligrosa de lo esperado." },
      { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "Código negro", description: "La unidad descubre que la operación real nunca fue rescatar a nadie, sino silenciar algo que no debía salir a la luz." },
      { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "Costa hostil", description: "Sin apoyo, con munición limitada y el enemigo cerrando rutas, avanzar por la costa se vuelve una sentencia." },
      { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "Bajo la línea de fuego", description: "Cada paso obliga a elegir entre salvar al equipo o seguir persiguiendo la verdad detrás del operativo." },
      { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "La lista de los muertos", description: "Un archivo recuperado del campamento enemigo revela nombres, pagos y oficiales vinculados a una cadena de traiciones." },
      { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "Objetivo comprometido", description: "La misión cambia por completo cuando entienden que el verdadero objetivo todavía sigue vivo." },
      { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "Nadie sale limpio", description: "La operación deja de ser militar y se convierte en una guerra sucia donde aliados y enemigos ya no se distinguen." },
      { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "Zona de quiebre", description: "Entre explosiones, persecuciones y confesiones, el grupo llega al punto donde toda lealtad empieza a romperse." },
      { num: 11, season: "temporada1", seasonLabel: "Temporada 1", title: "El precio del regreso", description: "Volver con vida tiene un costo inesperado cuando el enemigo demuestra que también controla la retaguardia." },
      { num: 12, season: "temporada1", seasonLabel: "Temporada 1", title: "La base sumergida", description: "Una instalación oculta frente al litoral confirma que la misión solo era la puerta de entrada a algo mucho mayor." },
      { num: 13, season: "temporada1", seasonLabel: "Temporada 1", title: "Traidor interno", description: "Las sospechas se transforman en certeza cuando uno de los suyos queda expuesto en plena fase crítica." },
      { num: 14, season: "temporada1", seasonLabel: "Temporada 1", title: "Operación ceniza", description: "La orden oficial es borrar todo rastro, incluso si para lograrlo deben eliminar a los sobrevivientes." },
      { num: 15, season: "temporada1", seasonLabel: "Temporada 1", title: "Sin extracción", description: "Abandonados por el mando, el equipo entiende que la única salida es abrirse paso por su cuenta." },
      { num: 16, season: "temporada1", seasonLabel: "Temporada 1", title: "La última carga", description: "Con el tiempo encima y la costa ardiendo, la ofensiva final se convierte en una carrera brutal contra la muerte." },
      { num: 17, season: "temporada1", seasonLabel: "Temporada 1", title: "El superviviente equivocado", description: "Cuando todo parece terminar, una revelación deja claro que la misión real apenas acaba de comenzar y abre el camino a la temporada 2." }
    ]
  },
  
  "codigos-de-calle-t1": {
    id: "codigos-de-calle-t1",
    title: "Códigos de Calle  Temporada 1",
    sagaTitle: "Códigos de Calle",
    description: "Una historia cruda de calle, poder, corrupción y traiciones en Santiago, donde nadie juega limpio y cada decisión puede costarte la vida.",
    cover: "../assets/covers/codigos-calle.jpg",
    baseFolder: "Thriller de corrupción/codigos-de-calle",
    defaultSeason: "temporada1",
    defaultSeasonLabel: "Temporada 1",
    freeChapters: 3,
    price: "$1.500 CLP",
    rating: 5,
    visitas: 0,
    tags: ["Thriller", "Calle", "Corrupción", "Suspenso", "Temporada 1"],
    chapters: [
      { num: 1, season: "temporada1", seasonLabel: "Temporada 1", title: "La noche del primer disparo", description: "Una ejecución en plena noche deja al descubierto que Santiago está a punto de explotar." },
      { num: 2, season: "temporada1", seasonLabel: "Temporada 1", title: "Lo que dejó el muerto", description: "Un hallazgo inesperado conecta a la calle con una red mucho más grande y peligrosa." },
      { num: 3, season: "temporada1", seasonLabel: "Temporada 1", title: "Nadie manda solo", description: "Las primeras traiciones revelan que detrás del negocio hay nombres que nadie se atreve a tocar." },
      { num: 4, season: "temporada1", seasonLabel: "Temporada 1", title: "La primera caída", description: "Una operación sale mal y obliga a mover piezas antes de tiempo." },
      { num: 5, season: "temporada1", seasonLabel: "Temporada 1", title: "Plata manchada", description: "El dinero empieza a correr mientras la violencia deja de ser una amenaza y se vuelve rutina." },
      { num: 6, season: "temporada1", seasonLabel: "Temporada 1", title: "Santiago no duerme", description: "La ciudad se convierte en un tablero donde todos vigilan a todos." },
      { num: 7, season: "temporada1", seasonLabel: "Temporada 1", title: "Los nombres prohibidos", description: "Una lista filtrada revela vínculos entre la calle, la política y la policía." },
      { num: 8, season: "temporada1", seasonLabel: "Temporada 1", title: "La deuda", description: "Viejas cuentas pendientes obligan a elegir entre lealtad y supervivencia." },
      { num: 9, season: "temporada1", seasonLabel: "Temporada 1", title: "Noche de ajuste", description: "Un ajuste de cuentas desata una guerra que ya nadie puede frenar." },
      { num: 10, season: "temporada1", seasonLabel: "Temporada 1", title: "Cara de traidor", description: "La traición aparece donde menos lo esperaban y cambia por completo el juego." },
      { num: 11, season: "temporada1", seasonLabel: "Temporada 1", title: "La ciudad cercada", description: "Con la presión encima, todos empiezan a cometer errores." },
      { num: 12, season: "temporada1", seasonLabel: "Temporada 1", title: "Código rojo", description: "Una orden interna deja claro que el enemigo no está solo afuera." },
      { num: 13, season: "temporada1", seasonLabel: "Temporada 1", title: "Bajo la misma sangre", description: "Los vínculos personales contaminan una guerra que debía ser solo de negocios." },
      { num: 14, season: "temporada1", seasonLabel: "Temporada 1", title: "Sin vuelta atrás", description: "Después de una decisión brutal, el conflicto cruza un punto irreversible." },
      { num: 15, season: "temporada1", seasonLabel: "Temporada 1", title: "El operativo", description: "Todo apunta a un cierre definitivo, pero las piezas no encajan del todo." },
      { num: 16, season: "temporada1", seasonLabel: "Temporada 1", title: "La captura", description: "La caída del objetivo parece cerrar la historia, aunque algo huele demasiado mal." },
      { num: 17, season: "temporada1", seasonLabel: "Temporada 1", title: "La falsa victoria", description: "Cuando todos creen que terminó, una verdad brutal revela que la captura fue una mentira." }
    ]
  }
};
